# Título(Cap) - Pense Estatística, 2º Edição.

## Universidade Federal de Alagoas - UFAL
## Centro de Tecnologia - CTEC
## Programa de Pós-Graduação Recursos Hídricos e Saneamento - PPGRHS
### Disciplina de Estatística

Clebson Farias

In [2]:
from __future__ import print_function, division

%matplotlib inline

import numpy as np
import pandas as pd

import thinkstats2
import thinkplot

In [3]:
#Dados Manso
dados = pd.read_csv("manso.csv", index_col=0, parse_dates=True)

            1455008  66210000  66231000  MANSO
1931-01-01      NaN       NaN       NaN    NaN
1931-01-02      NaN       NaN       NaN    NaN
1931-01-03      NaN       NaN       NaN    NaN
1931-01-04      NaN       NaN       NaN    NaN
1931-01-05      NaN       NaN       NaN    NaN
1931-01-06      NaN       NaN       NaN    NaN
1931-01-07      NaN       NaN       NaN    NaN
1931-01-08      NaN       NaN       NaN    NaN
1931-01-09      NaN       NaN       NaN    NaN
1931-01-10      NaN       NaN       NaN    NaN
1931-01-11      NaN       NaN       NaN    NaN
1931-01-12      NaN       NaN       NaN    NaN
1931-01-13      NaN       NaN       NaN    NaN
1931-01-14      NaN       NaN       NaN    NaN
1931-01-15      NaN       NaN       NaN    NaN
1931-01-16      NaN       NaN       NaN    NaN
1931-01-17      NaN       NaN       NaN    NaN
1931-01-18      NaN       NaN       NaN    NaN
1931-01-19      NaN       NaN       NaN    NaN
1931-01-20      NaN       NaN       NaN    NaN
1931-01-21      NaN       NaN       NaN    NaN
1931-01-22      NaN       NaN       NaN    NaN
1931-01-23      NaN       NaN       NaN    NaN
1931-01-24      NaN       NaN       NaN    NaN
1931-01-25      NaN       NaN       NaN    NaN
1931-01-26      NaN       NaN       NaN    NaN
1931-01-27      NaN       NaN       NaN    NaN
1931-01-28      NaN       NaN       NaN    NaN
1931-01-29      NaN       NaN       NaN    NaN
1931-01-30      NaN       NaN       NaN    NaN
...             ...       ...       ...    ...
2018-12-02      3.1       NaN       NaN    NaN
2018-12-03      0.0       NaN       NaN    NaN
2018-12-04      0.0       NaN       NaN    NaN
2018-12-05      0.0       NaN       NaN    NaN
2018-12-06      0.0       NaN       NaN    NaN
2018-12-07      0.0       NaN       NaN    NaN
2018-12-08      0.0       NaN       NaN    NaN
2018-12-09      0.0       NaN       NaN    NaN
2018-12-10      0.0       NaN       NaN    NaN
2018-12-11      0.0       NaN       NaN    NaN
2018-12-12      0.0       NaN       NaN    NaN
2018-12-13      0.0       NaN       NaN    NaN
2018-12-14      0.0       NaN       NaN    NaN
2018-12-15      0.0       NaN       NaN    NaN
2018-12-16      0.0       NaN       NaN    NaN
2018-12-17      9.5       NaN       NaN    NaN
2018-12-18     13.1       NaN       NaN    NaN
2018-12-19      0.0       NaN       NaN    NaN
2018-12-20      0.0       NaN       NaN    NaN
2018-12-21      0.0       NaN       NaN    NaN
2018-12-22      0.0       NaN       NaN    NaN
2018-12-23     12.5       NaN       NaN    NaN
2018-12-24     11.0       NaN       NaN    NaN
2018-12-25      0.0       NaN       NaN    NaN
2018-12-26      0.0       NaN       NaN    NaN
2018-12-27      0.0       NaN       NaN    NaN
2018-12-28      0.0       NaN       NaN    NaN
2018-12-29     17.0       NaN       NaN    NaN
2018-12-30      4.7       NaN       NaN    NaN
2018-12-31      0.0       NaN       NaN    NaN

[32142 rows x 4 columns]